### ISSUE TITLE
ccbi export: Trying to write string not added to cache ({path to file here})

### ISSUE THREAD

**Issue by kevinskyba** [cocos2d/CocosBuilder#168]
Version 2.1 (build from the website)

What I do:
- Create a new .ccb Sprite file
- Add one sprite frame animation to it ("Small Fishy/Small Fish 1.png") from GameElements.plist (Texture Packer)
- Publishing works!
- Now adding another sprite frame (at any frame) to it works, but publishing will crash with the error given in the title

What I tried to do already:
- Recreating every single .ccb file and creating a new project
- Re-organizing all graphic assets, including newest texture packer version etc.

Note: All my layer UI .ccb files work without any problem, they are beeing published, but as soon as this sprite file is meant to be published it crashes. Here is a link to the crash report: http://pastebin.com/71SgDZiS

I wanted to build the newest version from the dev or 2_1 branch, but unfortunately I'm not able to compile (tried everything you've written in the post about git submodule, still getting dependency issues and other errors). Is there any compiled dev build out there I can download to test if the error persists?

**Comment by kevinskyba** [comment]
I've noticed that publishing works, when I deactivate "Flatten paths when publishing". However, now my output consists of all kind of empty folders and my .ccbi files are in some subfolder. Am I doing anything wrong that it crashes when I activate the "Flatten paths when publishing" option?

I  can't use the .ccbi files like that, since all the resource paths are meant to be flat in my project.

**Comment by vlidholt** [comment]
I think this is now fixed (on develop branch)

**Comment by bonlam** [comment]
Seems this issue is not really fixed?

I have same issue with kevinskyba.
The updated build of CocosBuilder don't crash. But when reading the ccbi file, the "spritesheet" and "spriteFile" in function "parsePropTypeSpriteFrame" (CCNodeLoader.cpp, line 516) are both empty string. Leading to an immediate crash.

Or did I miss out something?
