### ISSUE TITLE
Animation type Instant doesn't work

### ISSUE THREAD

**Issue by therealhugocosta** [cocos2d/CocosBuilder#76]
Hi,

CocosBuilder pre-alpha 1
Tested on: iPad simulator and iPad 3 device

Choosing animation type "Instant" doesn't work on simulator or device, it produces the same result as "Linear" animation. It only works on CocosBuilder timeline player.

**Comment by vlidholt** [comment]
This is fixed on the latest release (2.1 alpha 0)

**Comment by yihuang** [comment]
I'm using HEAD version of CocosBuilder, but i still experience this bug.
